config/routes.rb
Rails.application.routes.draw do
  get 'messages/reply'

  get 'welcome/index'

  resources :rides do
    member do
      post 'toggle_payment_status'
    end
  end

  resources :messages do
  	collection do
  		post 'reply'
  	end
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
	validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  	skip_before_action :verify_authenticity_token
  	def reply
  		message_body = params["Body"]
  		from_number = params["From"]

      #names needs to not have spaces between the names/commas
  		date_string, price, names, payment_status  = message_body.split(" ")
      date_formatted = Date.strptime(date_string, "%m/%d/%Y")

      puts message_body
      count = names.split(",").length
      if payment_status == "paid"
        ride_complete = true
      else
        ride_complete = false
      end

  		boot_twilio

      #update page without refreshing

      if from_number == "+19167535026"
        puts "got in"
        Ride.create!(
        date: date_formatted,
        price: price,
        rider_names: names,
        rider_count: count,
        ride_complete: ride_complete)
      end

      # Ride.create!(
      #   date: date_formatted,
      #   price: price,
      #   rider_names: names,
      #   rider_count: count,
      #   ride_complete: ride_complete)

  		# if message_body == "Yessir"
			 #  sms = @client.messages.create(
    #   		from: Rails.application.secrets.twilio_number,
    #   		to: from_number,
    #   		body: "You said yessir"
    # 	)  			
  		# else
	  	# 	sms = @client.messages.create(
	   #    		from: Rails.application.secrets.twilio_number,
	   #    		to: from_number,
	   #    		body: "You didnt say yessir"
	   #  	)
	  	# end
  	end

  	private
  	def boot_twilio
    	account_sid = Rails.application.secrets.twilio_sid
    	auth_token = Rails.application.secrets.twilio_token
    	@client = Twilio::REST::Client.new account_sid, auth_token
  	end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

	def index
		@rides = Ride.all.order('date desc')
	end

	def show
		@ride = Ride.find(params[:id])
		puts @ride.ride_complete
	end

	def new
		@ride = Ride.new
	end

	def edit
		@ride = Ride.find(params[:id])
	end

	def create
		@ride = Ride.new(ride_params)
		
		if @ride.save
			redirect_to @ride
		else
			render 'new'
		end
	end

	def update
		@ride = Ride.find(params[:id])
		puts 'test'
		puts params[:ride_complete]
		puts 'end'
		puts 'ride_params: '
		puts ride_params[:ride_complete]
		puts 'end ride_params'
		# if params[:ride_complete]

		if @ride.update(ride_params)
			redirect_to @ride
			# render json: @ride
		else
			render 'edit'
		end
	end

	def toggle_payment_status
		@ride = Ride.find(params[:id])
		if @ride.update_attributes(:ride_complete => params[:payment_status])
			# render status: @ride.ride_complete, status: 200
			render :json => @ride.ride_complete
		else
			render :json => 'Error'
		end

	end


	def destroy
		@ride = Ride.find(params[:id])
		@ride.destroy

		redirect_to rides_path
	end

	private
	def ride_params
		params.require(:ride).permit(:date, :price, :rider_count, :rider_names, :ride_complete)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ridecharge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/reply.html.erb
<h1>Messages#reply</h1>
<p>Find me in app/views/messages/reply.html.erb</p>

app/views/rides/edit.html.erb
<h1>Edit RideCharge </h1>

<%= form_for(@ride) do |f| %>
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.ride.count, "error") %> prohibited
        this RideCharge from being saved:
      </h2>
      <ul>
        <% @ride.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :date, "Date of ride" %><br>
    <%= f.date_field :date %>
  </p>
 
  <p>
    <%= f.label :price, "Total ride price" %><br>
    <%= f.number_field :price %>
  </p>
 
  <p>
    <%= f.label :rider_names, "Rider names (separate by comma or space)" %> <br>
    <%= f.text_area :rider_names %>
  </p>

  <p>
    <%= f.label :rider_count, "Number of riders" %><br>
    <%= f.number_field :rider_count %>
  </p>


  <p>
    <%= f.label :ride_complete, "All participants have paid" %> <br>
    <%= f.check_box :ride_complete %>
  </p>  

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Delete RideCharge', ride_path(@ride), method: :delete, data: {confirm: 'Are you sure?'} %>

<%= link_to 'Back to All Rides', rides_path %>

app/views/rides/index.html.erb
<head>
	<%= stylesheet_link_tag "application" %>
</head>

<body>
	<div id="navbar">
		<div id="nav-title">RIDECHARGE</div>
			<div class="nav-section">
				<div class="nav-section-title">Home</div>
			</div>
			<div class="nav-section">
				<div class="nav-section-title">Profile</div>
			</div>
			<div class="nav-section">
				<div class="nav-section-title">Summary</div>
			</div>
	</div>


	
	<div id="content_title">All RideCharges</div>
	<div id="content">

 		<% @rides.each do |ride| %>

			<%= link_to ride_path(ride), class: (ride.ride_complete ? "ride_card paid" : "ride_card") do %>
					<div class="card_title"> <%= ride.date.strftime("%a %b %e") %> </br></div>
					<div class="card_content_container">
						<div class="card_section"> 
							<div class="card_section_title"> Price </br> </div>
							<div class="card_section_content"> <%= ride.price %> </div>
						</div>
						<div class="card_section"> 
							<div class="card_section_title"> # Riders </br> </div>
							<div class="card_section_content"> <%= ride.rider_count %> </div>
						</div>
						<div class="card_section">
							<div class="card_section_title"> Rider Names </br> </div>
							<div class="card_section_content"> <%= ride.rider_names %> </br> </div>
						</div>
					</div>
					<div class="payment_status">
						<span>Paid</span>
					</div>
			<% end %>

		<% end %>
	<%= link_to '+', new_ride_path, id: 'add_button' %>

	</div>
</body>

app/views/rides/new.html.erb
<h1>Add a new Ride</h1>


<%= form_for :ride, url: rides_path do |f| %>
  
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@ride.errors.count, "error") %> prohibited
        this RideCharge from being saved:
      </h2>
      <ul>
        <% @ride.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :date, "Date of ride" %><br>
    <%= f.date_field :date %>
  </p>
 
  <p>
    <%= f.label :price, "Total ride price" %><br>
    <%= f.number_field :price %>
  </p>
 
  <p>
    <%= f.label :rider_names, "Rider names (separate by comma or space)" %> <br>
    <%= f.text_area :rider_names %>
  </p>

  <p>
    <%= f.label :rider_count, "Number of riders" %><br>
    <%= f.number_field :rider_count %>
  </p>


  <p>
    <%= f.label :ride_complete, "All participants have paid" %> <br>
    <%= f.check_box :ride_complete %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to All Rides', rides_path %>

app/views/rides/show.html.erb
<p>
	<strong>Ride date: </strong>
	<%= @ride.date %>
</p>

<p>
	<strong>Number of riders: </strong>
	<%= @ride.rider_count %>
</p>

<p>
	<strong>Rider names: </strong>
	<%= @ride.rider_names %>
</p>

<p>
	<strong>Total ride price ($): </strong>
	<%= @ride.price %>
</p>

<div>
	<strong style="display: inline-block;">Payment complete? </strong>
	<div id="status" style="display: inline-block;">
		<%= @ride.ride_complete %>
	</div>
</div>

<%= check_box_tag 'payment_status', @ride.ride_complete, @ride.ride_complete, :data => {:id => @ride.id} %>
</br>

<%= link_to 'Edit RideCharge', edit_ride_path(@ride) %>
</br>
<%= link_to 'Delete RideCharge', ride_path(@ride), method: :delete, data: {confirm: 'Are you sure?'} %>
</br>

<%= link_to 'Back to All Rides', rides_path %>	

app/views/welcome/index.html.erb
<h1>Welcome to RideCharge!</h1>

<%= link_to 'See all ride charges', controller: 'rides' %>